
FROM node:20-alpine3.20 AS base

WORKDIR /app

# BUILDER STAGE
FROM base AS builder
COPY package*.json .
COPY tsconfig.json .
RUN npm install
COPY . .
RUN npm run build


# PRODUCTION STAGE
FROM base AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/tsconfig.json ./
RUN npm install --omit=dev
RUN NPM cache clean --force
EXPOSE 8000
CMD ["node", "dist/index.js"]
